version: "3.4"

services:
  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnet-app
    pull_policy: if_not_present
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dotnet-app.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
# https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-8.0
